### ISSUE TITLE
[BUG] Many BindExceptions when starting service

### ISSUE THREAD

**Issue by fxjordan** [rwth-acis/las2peer#118]
1. **Summary** - When I try to start a las2peer service locally on my machine I get a lot of `java.net.BindException`s which ultimately result in an StackOverflowError.
2. **Bug Details**
   1. **What?** - During startup, the application tries to bind to the port that is configured in the start script (9011), whch fails with a `BindException`. After that, it seems like the application tries to bind to all port numbers from 9012 to 11624 (see stack trace). Then, the application shows multiple times the same error `SocketPastryNodeFactory: Could not bind on any ports!java.lang.StackOverflowError` and finally crashes with a StackOverflowError.
   2. **Where?** - When starting the service.
   3. **When?/How often?** - Initially when I cloned and tried to run the Requirements Bazaar backend, but also reproduced with the unmodified las2peer template project. On macOS 10.15.17 with JAVA_HOME set to a JDK 14.
   4. **How?/Current state** - Reproduce by:
       - clone https://github.com/rwth-acis/las2peer-template-project
       - build using `./gradlew clean jar`
       - run using `./bin/start_network.sh`
       - Observer *a lot* of exceptions
3. **Fixed state** - Even if the problem is caused, e.g., by a firewall misconfiguration, there should be a more developer-friendly error message / exception.

**Error logs**
Shown after executing `./bin/start_network.sh`:
```
(base) felixjordan@Felixs-MBP las2peer-template-project % ./bin/start_network.sh
:rice.pastry.socket.internet:20211110.171233.587:Warning:  java.net.BindException: Address already in use:Felixs-MBP.fritz.box/192.168.178.74:9011
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.openServerSocket(UDPLayerImpl.java:200)
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.<init>(UDPLayerImpl.java:105)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:133)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:109)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:102)
	at rice.pastry.socket.SocketPastryNodeFactory.getWireTransportLayer(SocketPastryNodeFactory.java:458)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.getWireTransportLayer(RendezvousSocketPastryNodeFactory.java:443)
	at rice.pastry.socket.SocketPastryNodeFactory.getBottomLayers(SocketPastryNodeFactory.java:324)
	at rice.pastry.socket.SocketPastryNodeFactory.getNodeHandleAdapter(SocketPastryNodeFactory.java:351)
	at rice.pastry.transport.TransportPastryNodeFactory.nodeHandleHelper(TransportPastryNodeFactory.java:124)
	at rice.pastry.socket.SocketPastryNodeFactory.newNodeSelector(SocketPastryNodeFactory.java:1387)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:218)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:199)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.verifyConnectivityThenMakeNewNode(InternetPastryNodeFactory.java:497)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.newNodeSelector(InternetPastryNodeFactory.java:286)
	at rice.pastry.socket.SocketPastryNodeFactory$11.run(SocketPastryNodeFactory.java:1289)
	at rice.selector.SelectorManager.doInvocations(SelectorManager.java:443)
	at rice.selector.SelectorManager.run(SelectorManager.java:264)
:rice.pastry.socket.internet:20211110.171233.593:Warning:  java.net.BindException: Address already in use:Felixs-MBP.fritz.box/192.168.178.74:9012
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.openServerSocket(UDPLayerImpl.java:200)
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.<init>(UDPLayerImpl.java:105)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:133)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:109)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:102)
	at rice.pastry.socket.SocketPastryNodeFactory.getWireTransportLayer(SocketPastryNodeFactory.java:458)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.getWireTransportLayer(RendezvousSocketPastryNodeFactory.java:443)
	at rice.pastry.socket.SocketPastryNodeFactory.getBottomLayers(SocketPastryNodeFactory.java:324)
	at rice.pastry.socket.SocketPastryNodeFactory.getNodeHandleAdapter(SocketPastryNodeFactory.java:351)
	at rice.pastry.transport.TransportPastryNodeFactory.nodeHandleHelper(TransportPastryNodeFactory.java:124)
	at rice.pastry.socket.SocketPastryNodeFactory.newNodeSelector(SocketPastryNodeFactory.java:1387)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:218)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:199)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.verifyConnectivityThenMakeNewNode(InternetPastryNodeFactory.java:497)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.newNodeSelector(InternetPastryNodeFactory.java:286)
	at rice.pastry.socket.SocketPastryNodeFactory$11.run(SocketPastryNodeFactory.java:1289)
	at rice.selector.SelectorManager.doInvocations(SelectorManager.java:443)
	at rice.selector.SelectorManager.run(SelectorManager.java:264)
...
... ### continues until port 11624 ###...
...
:rice.pastry.socket.internet:20211110.171234.440:Warning:  java.net.BindException: Address already in use:Felixs-MBP.fritz.box/192.168.178.74:11624
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.openServerSocket(UDPLayerImpl.java:200)
	at org.mpisws.p2p.transport.wire.UDPLayerImpl.<init>(UDPLayerImpl.java:105)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:133)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:109)
	at org.mpisws.p2p.transport.wire.WireTransportLayerImpl.<init>(WireTransportLayerImpl.java:102)
	at rice.pastry.socket.SocketPastryNodeFactory.getWireTransportLayer(SocketPastryNodeFactory.java:458)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.getWireTransportLayer(RendezvousSocketPastryNodeFactory.java:443)
	at rice.pastry.socket.SocketPastryNodeFactory.getBottomLayers(SocketPastryNodeFactory.java:324)
	at rice.pastry.socket.SocketPastryNodeFactory.getNodeHandleAdapter(SocketPastryNodeFactory.java:351)
	at rice.pastry.transport.TransportPastryNodeFactory.nodeHandleHelper(TransportPastryNodeFactory.java:124)
	at rice.pastry.socket.SocketPastryNodeFactory.newNodeSelector(SocketPastryNodeFactory.java:1387)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:218)
	at rice.pastry.socket.nat.rendezvous.RendezvousSocketPastryNodeFactory.newNodeSelector(RendezvousSocketPastryNodeFactory.java:199)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.verifyConnectivityThenMakeNewNode(InternetPastryNodeFactory.java:497)
	at rice.pastry.socket.internet.InternetPastryNodeFactory.newNodeSelector(InternetPastryNodeFactory.java:286)
	at rice.pastry.socket.SocketPastryNodeFactory$11.run(SocketPastryNodeFactory.java:1289)
	at rice.selector.SelectorManager.doInvocations(SelectorManager.java:443)
	at rice.selector.SelectorManager.run(SelectorManager.java:264)
:rice.pastry.socket.internet:20211110.171234.446:SEVERE: SocketPastryNodeFactory: Could not bind on any ports!java.lang.StackOverflowError
:rice.pastry.socket.internet:20211110.171234.447:SEVERE: SocketPastryNodeFactory: Could not bind on any ports!java.lang.StackOverflowError
:rice.pastry.socket.internet:20211110.171234.447:SEVERE: SocketPastryNodeFactory: Could not bind on any ports!java.lang.StackOverflowError
:rice.pastry.socket.internet:20211110.171234.447:SEVERE: SocketPastryNodeFactory: Could not bind on any ports!java.lang.StackOverflowError
...
...
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:479)
	at java.base/java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:56)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LL.<init>(java/lang/invoke/BoundMethodHandle$Species_LL)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LL.make(java/lang/invoke/BoundMethodHandle$Species_LL)
	at java.base/java.lang.invoke.BoundMethodHandle$Species_LL.copyWith(java/lang/invoke/BoundMethodHandle$Species_LL)
	at java.base/java.lang.invoke.MethodHandle.viewAsType(MethodHandle.java:1646)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:280)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:259)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:376)
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:881)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:865)
	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:688)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:602)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:99)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:259)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:249)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1245)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1237)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1237)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1237)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1237)
	at rice.pastry.socket.SocketPastryNodeFactory.newNode(SocketPastryNodeFactory.java:1237)
...


```

**Comment by fxjordan** [comment]
Update: It seems like my Router is causing this error. If I disconnect from my Wi-Fi, I can start the service as expected.

But, why does the node try to bind to `Felixs-MBP.fritz.box/192.168.178.74:9011` in the first place? I'd expect it to use localhost by default
