### ISSUE TITLE
Unable to find IP for ISA

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer#61]
<p>Sometimes las2peer nodes do not start properly:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Waiting <span class="code-keyword">for</span> any bootstrap host to become available... Using pastry property file etc/pastry.properties ERROR: Unable to find IP <span class="code-keyword">for</span> ISA tech4comp.dbis.rwth-aachen.de:31014 - returning <span class="code-keyword">null</span>. Exception in thread <span class="code-quote">"main"</span> java.lang.NullPointerException  at rice.pastry.socket.internet.InternetPastryNodeFactory.<init>(InternetPastryNodeFactory.java:153)  at i5.las2peer.p2p.PastryNodeImpl.launchSub(PastryNodeImpl.java:229)  at i5.las2peer.p2p.Node.launch(Node.java:562)  at i5.las2peer.tools.L2pNodeLauncher.start(L2pNodeLauncher.java:805)  at i5.las2peer.tools.L2pNodeLauncher.launchConfiguration(L2pNodeLauncher.java:967)  at i5.las2peer.tools.L2pNodeLauncher.main(L2pNodeLauncher.java:1123)</pre>
</div></div>

<i>[LAS-470] created by neumann</i>

**Comment by AlexanderNeumann** [comment]
https://github.com/rwth-acis/las2peer/commit/bfa9d2824f5906ce24c6c27de0b336b2d8a84a75 fixed this issue.
